ApkaTa/ApkaTa/Controllers/RejestracjaController.cs
using ApkaTa.Models;
using ApkaTa.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;

namespace ApkaTa.Controllers
{
    public class RejestracjaController : Controller
    {

        public IUserRepository repo = new UserRepository();
        public IActionResult Loguj()
        {
            return RedirectToAction("Index", "Login");
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async  Task<IActionResult> Index(UserViewModel userViewModel)
        {
             List<UserViewModel> usr  = new List<UserViewModel>();
            ModelState["Płeć"].ValidationState = Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Valid;
            ModelState["Bmi"].ValidationState = Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Valid;
            ModelState["Waga"].ValidationState = Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Valid;
            ModelState["Wzrost"].ValidationState = Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Valid;
            
            
            if (ModelState.IsValid)
            {

                var temp = await repo.GetInfo();
                foreach (var i in temp)
                {
                    usr.Add(i);
                }
                var Temp = usr.Where(x => x.Email == userViewModel.Email || x.Nick == userViewModel.Nick).ToList();
                if (Temp.Count != 0)
                {
                    TempData["error"] = "Podane Email lub nick jest już zajęty!";

                    return View(userViewModel);
                }
                else if (userViewModel.Password != userViewModel.Bmi)
                {
                    TempData["error"] = "Podane hasła się różnią!";
                    return View(userViewModel);
                }
                else
                {
                    var user = new Users();
                    user.Email = userViewModel.Email;
                    user.Password = userViewModel.Password;
                    user.Nick = userViewModel.Nick;

                    var add = await repo.AddUserAccount(user);
                    if (add == false)
                    {
                        return View(userViewModel);
                    }
                    else
                    {
                        TempData["succes"] = "Konto zostało utworzone!";

                        return View();

                    }

                }
            }
            TempData["error"] = "Wprowadzone niepoprawne dane!!";
            return View(userViewModel);
        }
    }
}

ApkaTa/ApkaTa/Views/Rejestracja/Index.cshtml
@model ApkaTa.Models.UserViewModel
<html>
    <head>
    <link rel="stylesheet" href="/css/styleRej.css" />
    </head>
<body>
<div class="main">
    <div class="Tytul">
        <h1>Rejestracja</h1>

    </div>
    
            @using (Html.BeginForm("Index", "Rejestracja", FormMethod.Post))
            {
            @if (TempData["succes"] != null)
            {
                <div class="alert">
                    <strong> Sukces</strong> @TempData["succes"]
                </div>
            }
            @if (TempData["Error"] != null)
            {
                <div class="alert-error">
                    <strong> Bład</strong> @TempData["Error"]
                </div>
            }
        <div class="Formularz">
            <div class="daneTxt">
                <input type="text" class="inputDane" placeholder="Email" asp-for="Email" />
                    @Html.ValidationMessageFor(model => model.Email)

            </div>


            <div class="daneTxt">
                <input type="text" class="inputDane" placeholder="Nick" asp-for="Nick" />
                @Html.ValidationMessageFor(model => model.Nick)

            </div>


            <div class="daneTxt">
                <input type="password" id="pass1" class="inputDane" placeholder="Hasło" asp-for="Password"/>
                 @Html.ValidationMessageFor(model => model.Password)

            </div>


            <div class="daneTxt">
                <input type="password" class="inputDane" placeholder="Powtórz Hasło" asp-for="Bmi" />
                 @Html.ValidationMessageFor(model => model.Password)

            </div>

            <div class="Info">
                <p>Posiadasz już konto? <a asp-action="Loguj">Zaloguj</a></p>
            </div>

        </div>
        <div class="btnRej">
            <input type="submit" value="Zajerestruj się!" />
        </div>
        }
    
</div>

    </body>
</html>