ApkaTa/ApkaTa/Models/Aktywność.cs
namespace ApkaTa.Models
{
    public class Aktywność
    {
        public int IdAktywności { get; set; }
        public string Nazwa { get; set; }
        public string Obrazek { get; set; }
    }
}

ApkaTa/ApkaTa/Controllers/AktywnośćController.cs
using ApkaTa.Models;
using ApkaTa.Services;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using System.Security.Cryptography.X509Certificates;
using System.Security.Claims;

namespace ApkaTa.Controllers
{
    [Authorize]

    public class AktywnośćController : Controller
    {
        readonly IAktywnośćRepository aktywnoscRepository = new AktywnośćRepository();
        readonly IUserRepository userRepository = new UserRepository();
        public UserViewModel _User { get; set; } = new();

        public List<AktywnośćUserModel> Zaaplanowane { get; } = new();
        public List<AktywnośćUserModel> ZaplanowanaSearch { get; } = new();
        public List<AktywnośćUserModel> Dostepna { get; } = new();
        public List<AktywnośćUserModel> DostepnaSearch { get; } = new();
        public List<AktywnośćUsr> LastAktywność { get; } = new();

        public List<SelectListItem> AktywnośćP { get; } = new();
        public async void GetInfo()
        {
            ViewBag.IdU = Convert.ToInt16(User.FindFirstValue(ClaimTypes.NameIdentifier));

            var user = await userRepository.GetUserId(ViewBag.IdU);
            _User = user;
            ViewBag.Nick = _User.Nick;

        }
        public async Task<IActionResult> Index()
        {
            
            ViewBag.IdU = Convert.ToInt16(User.FindFirstValue(ClaimTypes.NameIdentifier));
           
            var user = await userRepository.GetUserId(ViewBag.IdU);
            _User = user;
            return View(_User);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DodajAktywność(string NazwaAktywnosc, AktywnośćUser aktywność)
        {
            
            ViewBag.IdU = Convert.ToInt16(User.FindFirstValue(ClaimTypes.NameIdentifier));
            GetInfo();
            if (ModelState.IsValid)
            {

                if (aktywność.GodzinaOd > aktywność.GodzinaDo)
                {
                    TempData["Error"] = "Czas trwania wydarenia musi trwać min. 30 minut!";
                    if (ViewBag.NazwaAktywnosc is null)
                    {
                        var items = await aktywnoscRepository.GetAktywności();
                        ViewBag.NazwaAktywnosc = new List<SelectListItem>();

                        foreach (var it in items)
                        {
                            ViewBag.NazwaAktywnosc.Add(new SelectListItem { Text = it.Nazwa, Value = it.IdAktywności.ToString() });
                        }
                    }
                    return View(aktywność);
                }

                var TimeResult = aktywność.GodzinaDo - aktywność.GodzinaOd;
                TimeSpan time = new TimeSpan(0, 30, 0);
                if (TimeResult > time)
                {
                    var active = new AktywnośćUser()
                    {
                        IdAktywności = Convert.ToInt16(NazwaAktywnosc),
                        GodzinaOd = aktywność.GodzinaOd,
                        GodzinaDo = aktywność.GodzinaDo,
                        Data = aktywność.Data,
                        MiejsceDoc = aktywność.MiejsceDoc,
                        IlośćMiejsc = aktywność.IlośćMiejsc,
                        Opis = aktywność.Opis

                    };
                    if (await aktywnoscRepository.AddAktywnośćUser(active))
                    {
                        var result = await aktywnoscRepository.GetLastAktywność();
                        foreach (var pik in result)
                        {
                            LastAktywność.Add(pik);
                        }
                        LastAktywność[0].IdU = ViewBag.IdU;
                        if (await aktywnoscRepository.AddAktywnośćUsr(LastAktywność[0]))
                        {
                            TempData["succes"] = "Wydarzenie zostało dodane!";
                            return RedirectToAction("NadchodzaceWyd");
                        }
                        else
                        {
                            TempData["error"] = "Coś poszło nie tak.. Serwer jest niosiągalny!";
                            return RedirectToAction("NadchodzaceWyd");
                        }

                    }
                }

            }
            TempData["error"] = "Wypełnij wszystkie pola formularza!";

            if (ViewBag.NazwaAktywnosc is null)
            {
                var items = await aktywnoscRepository.GetAktywności();
                ViewBag.NazwaAktywnosc = new List<SelectListItem>();

                foreach (var it in items)
                {
                    ViewBag.NazwaAktywnosc.Add(new SelectListItem { Text = it.Nazwa, Value = it.IdAktywności.ToString() });
                }
            }
            return View(aktywność);
        }


        [HttpGet]
        public async Task<IActionResult> DodajAktywność()
        {
            GetInfo();

            if (ViewBag.NazwaAktywnosc is null)
            {
                var items = await aktywnoscRepository.GetAktywności();
                ViewBag.NazwaAktywnosc = new List<SelectListItem>();

                foreach (var it in items)
                {
                    ViewBag.NazwaAktywnosc.Add(new SelectListItem { Text = it.Nazwa, Value = it.IdAktywności.ToString() });
                }
            }
            ViewBag.DataMin = DateTime.Now.Date.ToString("yyyy-MM-dd");
            ViewBag.DateMax = DateTime.Now.Date.AddDays(13).ToString("yyyy-MM-dd");
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> DostepneAkty(string NazwaAktywnosc)
        {
            ViewBag.IdU=Convert.ToInt16(User.FindFirstValue(ClaimTypes.NameIdentifier));

            GetInfo();


            if (ViewBag.NazwaAktywnosc is null)
            {
                var items = await aktywnoscRepository.GetAktywności();
                ViewBag.NazwaAktywnosc = new List<SelectListItem>();

                foreach (var it in items)
                {
                    ViewBag.NazwaAktywnosc.Add(new SelectListItem { Text = it.Nazwa, Value = it.Nazwa });
                }
            }


            var DosAkty = await aktywnoscRepository.GetDostępneAktywności(ViewBag.IdU);
            foreach (var dostepna in DosAkty)
            {
                Dostepna.Add(dostepna);
            }


            if (Dostepna.Count == 0)
            {
                return View();

            }
            else
            {
                if (string.IsNullOrEmpty(NazwaAktywnosc))
                {
                    TempData["MessageWpisy"] = "Wybierz kategorię aktywności!";
                    return View(Dostepna);
                }
                else
                {
                    if (DostepnaSearch != null) DostepnaSearch.Clear();
                    var result = Dostepna.Where(x => x.Nazwa == NazwaAktywnosc).ToList();
                    foreach (var item in result)
                    {
                        DostepnaSearch.Add(item);
                    }
                    return View(DostepnaSearch);

                }
            }
            return View(Dostepna);
        }

        [HttpGet]
        public async Task<IActionResult> NadchodzaceWyd(string NazwaAktywnosc)
        {
            ViewBag.IdU = Convert.ToInt16(User.FindFirstValue(ClaimTypes.NameIdentifier));
            GetInfo();
            if (ViewBag.NazwaAktywnosc is null)
            {
                var items = await aktywnoscRepository.GetAktywności();
                ViewBag.NazwaAktywnosc = new List<SelectListItem>();

                foreach (var it in items)
                {
                    ViewBag.NazwaAktywnosc.Add(new SelectListItem { Text = it.Nazwa, Value = it.Nazwa });
                }
            }


            var NadAkty = await aktywnoscRepository.GetNadchodzącaAktywności(ViewBag.IdU);
            foreach (var Nadch in NadAkty)
            {
                Zaaplanowane.Add(Nadch);
            }
          
            if (Zaaplanowane.Count == 0)
            {
                return View();

            }
            else
            {
                if (string.IsNullOrEmpty(NazwaAktywnosc))
                {
                    TempData["MessageWpisy"] = "Wybierz kategorię aktywności!";
                    return View(Zaaplanowane);
                }
                else
                {
                    if (ZaplanowanaSearch != null) ZaplanowanaSearch.Clear();
                    var result = Zaaplanowane.Where(x => x.Nazwa == NazwaAktywnosc).ToList();
                    foreach (var item in result)
                    {
                        ZaplanowanaSearch.Add(item);
                    }
                    return View(ZaplanowanaSearch);

                }
            }
        }


        [HttpGet]
        public async Task<IActionResult> DostepnaUserDetalies(int id)
        {
            ViewBag.IdU = Convert.ToInt16(User.FindFirstValue(ClaimTypes.NameIdentifier));
            GetInfo();
            var Nadchodzaca = await aktywnoscRepository.GetDostępneAktywności(ViewBag.IdU);
            foreach (var aktyNad in Nadchodzaca)
            {
                Dostepna.Add(aktyNad);
            }
            var detaliesPost = Dostepna.Where(x => x.AktywnośćId == id).ToList();
            AktywnośćUserModel detalise = detaliesPost[0];
            return View(detalise);
        }


        [HttpPost]
        public async Task<IActionResult> Dolacz(int id, AktywnośćUserModel akty)
        {
            ViewBag.IdU = Convert.ToInt16(User.FindFirstValue(ClaimTypes.NameIdentifier));

            if (akty.IlośćMiejsc != akty.Count)
            {
                var aktywnosc = new AktywnośćUsr();
                aktywnosc.AktywnośćId = id;

ApkaTa/ApkaTa/Views/Aktywność/DodajAktywność.cshtml
@model ApkaTa.Models.AktywnośćUser

<link rel="stylesheet" href="/css/Dodawanie.css" />
<script src="https://kit.fontawesome.com/37dde7df60.js" crossorigin="anonymous"></script>


<body>

	<div id="container">

		<div class="navbar">
			<li>
				<h2>Aktywni Fizycznie </h2>
			</li>
			<ul>
				<li>Witaj @ViewBag.Nick  <i class="fa-solid fa-user"></i></li>
			</ul>
		</div>
		<div class="PanelBoczny">

			<ul>
				<li>
					<a asp-action="Index">
						<i class="fa-solid fa-house-user"></i><span class="item">Home Page</span>
					</a>
				</li>
				<li><a asp-action="Profil"><i class="fas fa-user"></i><span class="item">Profil</span></a></li>
				<li><a asp-action="Index"><i class="fa-solid fa-person-running"></i><span class="item">Aktywność</span></a></li>
				<li><a asp-action="Ustawienia"><i class="fa-solid fa-gears"></i><span class="item">Ustawienia</span></a></li>
				<li><a asp-action="Wpisy"><i class="fa-sharp fa-solid fa-blog"></i><span class="item">Wpisy</span></a></li>
				<li><a asp-action="About"><i class="fa-solid fa-circle-info"></i><span class="item">O nas</span></a></li>
				<li><a class="Wyloguj" asp-action="Wyloguj"><i class="fa-solid fa-right-from-bracket"></i><span class="item">Wyloguj</span></a></li>
			</ul>

		</div>
		<div class="main">
			<div class="Profil">
				<div class="naglowek">
					<img src="../Images/active1.svg" width="30%" />
					<h2> Dodaj Wydarzenie Aktywnościowy	</h2>
				</div>

				 @using (Html.BeginForm("DodajAktywność", "Aktywność", FormMethod.Post)){
					 @if (TempData["AlertMessage"] != null){
								<div class="alert">
									<strong> Sukces</strong> @TempData["AlertMessage"]
								</div>
							}
								@if (TempData["error"] != null)
								{
									<div class="alert-error">
										<strong> Bład</strong> @TempData["Error"]
									</div>
								}
				<div class="formularz">

					<div class="daneTxt">
						<label> Nazwa Aktywności </label>
							@Html.DropDownList("NazwaAktywnosc",(SelectList)ViewBag.NazwaAktywnosci,"Wybierz Aktywność", new {@class = "inputDane"})
							@Html.ValidationMessageFor(model => model.IdAktywności)

					</div>

					<div class="daneTxt">
						<div class="Godziny">
							<label> Godzina Od </label>
							<input type="time" class="inputDane" asp-for="GodzinaOd" />
								@Html.ValidationMessageFor(model => model.GodzinaOd)

						</div>
						<div class="GodzinyDo">
							<label> Godzina Od </label>
							<input type="time" class="inputDane" asp-for="GodzinaDo"  />
								@Html.ValidationMessageFor(model => model.GodzinaDo)

						</div>
					</div>
				</div>
				<div class="daneTxt" style="clear:both;">
					<label> Data </label>
						<input type="date" class="inputDane" asp-for="Data" min="@DateTime.Now.Date.ToString("yyyy-MM-dd")" max="@DateTime.Now.Date.AddDays(13).ToString("yyyy-MM-dd")" />
						  @Html.ValidationMessageFor(model => model.Data)

				</div>
				<div class="daneTxt" style="clear:both;">
					<label> Miejsce </label>
					<input type="text" class="inputDane" asp-for="MiejsceDoc" />
						@Html.ValidationMessageFor(model => model.MiejsceDoc)

				</div>
				<div class="daneTxt" style="clear:both;">
					<label> Ilość miejsc </label>
					<input type="number" class="inputDane" asp-for="IlośćMiejsc" />
						@Html.ValidationMessageFor(model => model.IlośćMiejsc)

				</div>
				<div class="OpisTxt">
					<label> Opis </label>
					<textarea class="Opis" rows=4  asp-for="Opis" > </textarea>
						@Html.ValidationMessageFor(model => model.Opis)

				</div>

				<div class="btnRej">
					<input type="submit" value="Dodaj!" />
				</div>
				}
			</div>
		</div>
	</div>






	
	

</body>














  

ApkaTa/ApkaTa/Views/Aktywność/DostepnaUserDetalies.cshtml
@model ApkaTa.Models.AktywnośćUserModel

<html lang="pl">


	<link rel="stylesheet" href="/css/Detalies.css" />
	<script src="https://kit.fontawesome.com/37dde7df60.js" crossorigin="anonymous"></script>

<body>

	<div id="container">

		<div class="navbar">
			<li>
				<h2>Aktywni Fizycznie </h2>
			</li>
			<ul>
				<li>Witaj @ViewBag.Nick  <i class="fa-solid fa-user"></i></li>
			</ul>
		</div>
		<div class="PanelBoczny">

			<ul>
				<li>
					<a asp-action="Index">
						<i class="fa-solid fa-house-user"></i><span class="item">Home Page</span>
					</a>
				</li>
				<li><a asp-action="Profil"><i class="fas fa-user"></i><span class="item">Profil</span></a></li>
				<li><a asp-action="Index"><i class="fa-solid fa-person-running"></i><span class="item">Aktywność</span></a></li>
				<li><a asp-action="Ustawienia"><i class="fa-solid fa-gears"></i><span class="item">Ustawienia</span></a></li>
				<li><a asp-action="Wpisy"><i class="fa-sharp fa-solid fa-blog"></i><span class="item">Wpisy</span></a></li>
				<li><a asp-action="About"><i class="fa-solid fa-circle-info"></i><span class="item">O nas</span></a></li>
				<li><a class="Wyloguj" asp-action="Wyloguj"><i class="fa-solid fa-right-from-bracket"></i><span class="item">Wyloguj</span></a></li>
			</ul>

		</div>
		<div class="main">
			<div class="Profil">
				<div class="naglowek">
					<img src="/Images/@Model.Obrazek" width="15%" />
					<h2> @Model.Nazwa	</h2>
				</div>
				@using (Html.BeginForm("Dolacz", "Aktywność", FormMethod.Post)){
				<div class="formularz">

					<div class="daneTxt">
						<div class="Godziny">
							<label> Godzina Od </label>
							<input type="time" class="inputDane" asp-for="GodzinaOd" readonly />
						</div>
						<div class="GodzinyDo">
							<label> Godzina Od </label>
							<input type="time" class="inputDane" asp-for="GodzinaDo" readonly />

						</div>
					</div>

					

						<div class="daneTxt" style="clear:both;">
						<label> Data </label>
							<input type="text" class="inputDane" asp-for="Data" value="@Model.Data.ToString("dd-MM-yyyy")" readonly />
					</div>

					<div class="daneTxt">
						<label> Miejsce Docelowe </label>
							<input type="text" class="inputDane" asp-for="MiejsceDoc" value="@Model.MiejsceDoc" readonly />
					</div>

					<div class="daneTxt">
						<label> Ilość uczestników </label>
							<input type="text" class="inputDane" asp-for="IlośćMiejsc" value="@Model.IlośćMiejsc" readonly />
					</div>

					<div class="OpisTxt">
						<label> Opis </label>
							<textarea class="Opis" rows=4 asp-for="Opis" readonly> @Model.Opis </textarea>
					</div>


				</div>
					
			
				<div class="btnRej">
					<input type="submit" value="Dołącz!" asp-action="Dolacz" asp-route-id="@Model.AktywnośćId" asp-controller="Aktywność" />
				</div>
			}
			</div>
		</div>






	</div>
	

</body>







@*@using (Html.BeginForm("Dolacz", "Aktywność", FormMethod.Post))
{
    <input type="text" class="form-control" asp-for="IlośćMiejsc" value="@Model.IlośćMiejsc" />
    <input type="text" class="form-control" asp-for="Count" value="@Model.Count" />
    

    <button asp-action="Dolacz" asp-route-id="@Model.AktywnośćId" asp-controller="Aktywność" class=" btn btn-light"> Dołącz do Wydarzenia</button>

  }*@

ApkaTa/ApkaTa/Views/Aktywność/DostepneAkty.cshtml
@model List<ApkaTa.Models.AktywnośćUserModel>

<html lang="pl">

<head>
    <link rel="stylesheet" href="/css/site.css" />
    <script src="https://kit.fontawesome.com/37dde7df60.js" crossorigin="anonymous"></script>
    <style>
        body {
            background-image: url(../Images/back.jpg);
            background-size: cover;
            width: 100%;
            height: 100%;
        }


        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            list-style: none;
            text-decoration: none;
            font-family: 'Josefin Sans', sans-serif;
        }


        h2 {
            top: 10px;
            text-align: center;
            font-size: 29px;
            color: black;
        }

        .navbar {
            align-items: center;
            display: flex;
            justify-content: space-between;
            margin-right: 0px;
        }

            .navbar li, h2 {
                font-size: 35px;
                color: white;
                padding: 43px;
            }

        .PanelBoczny {
            outline: none;
            position: absolute;
            bottom: auto;
            height: auto;
            left: 0;
            background-color: whitesmoke;
            width: 130px;
            overflow: hidden;
        }

        a {
            position: relative;
            font-size: 14px;
            display: table;
            width: 290px;
            padding: 30px;
            color: Gray;
        }

        .fas {
            width: 70px;
            position: relative;
            height: 40px;
            top: 14px;
            text-align: center;
            font-size: 50px;
        }

        .fa-solid {
            width: 70px;
            position: relative;
            height: 40px;
            top: 14px;
            text-align: center;
            font-size: 50px;
        }

        .item {
            top: 15px;
            font-size: 24px;
            margin-left: 29px;
        }

        a:hover {
            background-color: lightgray;
        }

        .PanelBoczny:hover {
            width: 280px;
        }

        .PanelBoczny ul li {
            border-bottom: 1px solid rgb(128, 128, 128);
            border-top: 1px solid rgb(128, 128, 128);
        }


        #footer {
            position: fixed;
            padding: 10px 10px 0px 10px;
            bottom: 0;
            width: 100%;
            /* Height of the footer*/
            height: 40px;
            background: grey;
            clear: both
        }

        .content {
            margin-left: 15%;
            padding: 30px;
            font-size: 25px;
            color: black;
            text-align: center;
            width: auto;
            top: 10%;
        }


        .BtnTxt {
            height: 100%;
            width: 100%;
            border-radius: 25px;
            background: skyblue;
            position: absolute;
        }


        .btn:hover .BtnTxt {
            width: 100%;
            border: none;
        }

        .h1 {
            text-align: center;
        }

        .input {
            width: 500px;
            height: 50px;
        }

        .content .NadWyd table {
            text-align: center;
            width: 95%;
            height: 20%;
        }

            .content .NadWyd table a {
                width: 95%;
                opacity: 0.5;
            }

        .content .historiaWyd table {
            width: 95%;
            height: 20%;
        }

        .content .pogodaWyd table {
            width: 95%;
            height: 15%;
            text-align: center;
        }

        .main {
            position: absolute;
            right: 1%;
            left: 12%;
            padding: 3%;
            height: 100%;
            width: auto;
            font-weight:bold;
            border: 3px blue;
            opacity: 0.7;
        }

        .Tytul {
            margin-top: 15%;
            height: 5%;
            font-size: 80%;
            text-align: center;
            margin-bottom: 30px;
        }

        .inputDane {
        }

        .Formularz {
            margin-top: 10%;
            display: absolute;
        }

        .inputDane {
            width: 100%;
            height: 45px;
            margin-top: 20px;
            padding: 5px;
        }

        input:focus {
            border: 1px solid skyblue;
            box-shadow: 0 0 3px #1670BE;
            outline-offset: 0px;
            outline: none;
        }

        .main .btnRej input {
            width: 50%;
            float: right;
            height: 50px;
            background-color: skyblue;
            border: 0px;
            margin-top: 10px;
        }

        .main .Formularz .Info p {
            text-align: center;
            font-family: Arial;
            font-size: 14px;
        }


        .btn {
            width: 45%;
            height: 50px;
            text-align: center;
            border-radius: 35px;
            padding: 6% 0;
            margin: 5% 2%;
            font-weight: bold;
            background-color: lightblue;
            color: White;
            cursor: pointer;
            position: relative;
            border-color: skyblue;
        }

        .headerSearch {
            height: 10%;
        }

            .headerSearch form {
                padding: 1%;
                height: 100%;
                width: 58%;
            }


            .headerSearch select {
                width: 70%;
                height: 100%;
            }

            .headerSearch button {
                height: 100%;
                float: right;
                width: 28%;
                border-radius: 25px;
                background: skyblue;
                border-color: skyblue;
                color: white;
            }

        .gridView {
            height: 80%;
            text-align:center;
        }

        .span {
            font-size: 22px;
        }

        .alert {
            background-color: lightgreen;
            height: 50px;
            text-align: center;
            color: white;
            border-radius: 10px;
            display: block;
            line-height: 50px;
            font-size: large;
        }

        .alert-error {
            background-color: lightcoral;
            height: 50px;
            text-align: center;
            color: white;
            border-radius: 10px;
            display: block;
            line-height: 50px;
            font-size: large;
        }
        .BtnPrzeg
        {
        width: 35%;
        background: skyblue;
        border-radius: 25px;
        height: auto;
        padding: 30px;
        margin-left: 15%;
        color:black;
        font-weight:900;
        }
        .tableView{
            width: 100%;
            color: black;
            font-weight: 900;
            font-size: x-large;
            background-color:whitesmoke;
            opacity: 0.9;
        }
            

    </style>
</head>
<body>

    <div id="container">

        <div class="navbar">
            <li>
                <h2>Aktywni Fizycznie </h2>
            </li>
            <ul>
                <li> @ViewBag.Nick <i class="fa-solid fa-user"></i></li>
            </ul>
        </div>
        <div class="PanelBoczny">

            <ul>
                <li>
                    <a asp-action="Index">
                        <i class="fa-solid fa-house-user"></i><span class="item">Home Page</span>
                    </a>
                </li>
                <li><a asp-action="Profil"><i class="fas fa-user"></i><span class="item">Profil</span></a></li>
                <li><a asp-action="Index"><i class="fa-solid fa-person-running"></i><span class="item">Aktywność</span></a></li>
                <li><a asp-action="Ustawienia"><i class="fa-solid fa-gears"></i><span class="item">Ustawienia</span></a></li>
                <li><a asp-action="Wpisy"><i class="fa-sharp fa-solid fa-blog"></i><span class="item">Wpisy</span></a></li>
                <li><a asp-action="About"><i class="fa-solid fa-circle-info"></i><span class="item">O nas</span></a></li>
                <li><a class="Wyloguj" asp-action="Wyloguj"><i class="fa-solid fa-right-from-bracket"></i><span class="item">Wyloguj</span></a></li>
            </ul>

        </div>
        <div class="main">

            <div class="headerSearch">
                @using (Html.BeginForm("DostepneAkty", "Aktywność", FormMethod.Get))
                {

                    @Html.DropDownList("NazwaAktywnosc",(SelectList)ViewBag.NazwaAktywnosci,"Wybierz Aktywność")
                    <button type="submit" asp-action="DostepneAkty" asp-controller="Aktywność"> Wyszukaj </button>
                }
            </div>
            @if (TempData["succes"] != null)
            {
                <div class="alert">
                    <strong> Sukces</strong> @TempData["succes"]
                </div>
            }
            @if (TempData["error"] != null)
            {
                <div class="alert-error">
                    <strong> Sukces</strong> @TempData["error"]
                </div>
            }
            <div class="gridView">
                <table class="tableView" >
                    <thead>
                        <tr style="width:100%;">
                            <td> </td>
                            <td> Nazwa </td>
                            <td> Data </td>
                            <td> Ilość miejsc </td>
                            <td> Zajęte </td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            @foreach (var akty in Model)
                            {
                                <tr>
                                    <td width="150"><img src="../../Images/@akty.Obrazek" width="150" height="150" /></td>
                                    <td style="margin-top:50%"><center>@akty.Nazwa</center></td>
                                    <td>@akty.Data.ToString("dd-MM-yyyy")</td>
                                    <td>@akty.IlośćMiejsc</td>
                                    <td>@akty.Count</td>
                                    <td>
                                        <td>
                                            <div class="">
                                                <a asp-action="DostepnaUserDetalies" asp-route-id="@akty.AktywnośćId" class="BtnPrzeg"> Przeglądaj</a>

                                            </div>
                                        </td>
                                </tr>

                            }
                        }
                    </tbody>
                    
                </table>
                @if (Model == null)
                {
                    <h1 style="color:white; margin-top:10%;">Nie ma aktualnie dostępnych Wydarzeń!</h1>
                }
            </div>
        </div>

    </div>
   

</body>
</html>